import type { Metadata } from 'next'
import './globals.css'
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'

export const metadata: Metadata = {
  title: 'Digital Photobooth',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning className='h-full'>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} w-full h-full min-h-screen relative bg-neutral-950`}
      >
        {/* Background Gradient */}
        <div className='absolute top-0 left-0 w-full h-full bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.3),rgba(255,255,255,0))]'></div>

        {/* Main Content */}
        <div className='relative z-10 '>{children}</div>
      </body>
    </html>
  )
}
