import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import AnimatedBackground from "@/components/animated-background";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Flash Studio - James Anquillano",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} w-full  min-h-screen relative bg-neutral-950`}
      >
        <Header />
        {/* Main Content */}
        <div className="relative z-10 ">{children}</div>
      </body>
    </html>
  );
}
