import type { Metadata } from 'next'
import './globals.css'
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'
import Footer from './components/Footer'

export const metadata: Metadata = {
  title: 'Digital Photo Booth',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable}  py-[3rem] px-[8rem] `}
      >
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  )
}
